[Interface]
# Kunci privat untuk VPN Server (dapat dibuat dengan command: wg genkey)
PrivateKey = 2LwC4AujakKc2O23qwrC36nwnMIkrReIJA12nry/L1I=

# IP Address untuk interface WireGuard server
Address = 10.8.0.1/24

# Port WireGuard listen
ListenPort = 51820

# Aturan IPTables dinamis untuk meneruskan lalu lintas (IP forwarding & NAT/Masquerading)
# Aturan ini melakukan Masquerade untuk semua paket yang berasal dari subnet 10.8.0.0/24
# ketika paket tersebut keluar melalui interface eksternal sistem.
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -j MASQUERADE

# Contoh konfigurasi Client/Peer (silakan disesuaikan dan hapus tanda '#' untuk menggunakan)
[Peer]
PublicKey = mXSuE6+Y6UdGnEqZKqpzEGOx344YdLD2uW77KB/LjWo=
AllowedIPs = 10.8.0.2/32
